[package]
name = "arrow-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "28.0.0"
bytes = "1.3"
parquet = { version = "28.0.0", features = ["async"] }
futures = "0.3"